version: '3'
services:
  backend:
    build: ./expressjs
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mernproject  # Change the port here
    depends_on:
      - mongo

  frontend:
    build: ./orsfe
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27019:27017"  # Map host port 27018 to container port 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: